export function createInitialState() {
  return {
    route: "dashboard",
    user: null,
    provider: "",
    toast: "",
    aiAnswer: "",
    messages: [],
    activity: [],
    loading: {
      session: false,
      dashboard: false,
      assignments: false,
      questionBanks: false,
      practice: false,
      analytics: false,
      collaboration: false,
      settings: false
    },
    saving: {
      assignment: false,
      grading: false,
      questionBank: false,
      question: false,
      practiceAnswer: false,
      profile: false,
      submission: false,
      reminder: false,
      knowledgePath: false,
      knowledgePractice: false,
      knowledgeContext: false,
      adaptivePlan: false,
      collaborationRoom: false,
      collaborationMessage: false,
      collaborationReply: false,
      collaborationTask: false,
      collaborationSummary: false,
      collaborationMember: false,
      collaborationDecision: false,
      collaborationResource: false,
      collaborationChecklist: false,
      collaborationHandoff: false,
      classroom: false,
      classAssignment: false,
      group: false,
      groupMember: false,
      identityProfile: false
    },
    errors: {},
    filters: {
      assignments: { courseId: "", status: "", keyword: "" },
      questionBanks: { courseId: "", type: "", difficulty: "", keyword: "" },
      practice: { courseId: "", bankId: "", status: "", mistakeStatus: "" },
      analytics: { courseId: "", studentId: "" },
      workbench: { courseId: "", category: "", reminderStatus: "" },
      knowledge: { courseId: "", query: "object collaboration", category: "", difficulty: "", tag: "", conceptId: "" },
      assessmentInsight: { courseId: "", assignmentId: "", rubricId: "", submissionId: "", practiceSessionId: "", mistakeId: "", studentId: "" },
      collaboration: { courseId: "", roomId: "", type: "", taskStatus: "", mentionStatus: "" },
      reports: { courseId: "", studentId: "", assignmentId: "", format: "markdown" },
      identityAdmin: { role: "", status: "", courseId: "", classroomId: "", q: "" }
    },
    selected: {
      assignmentId: "",
      questionBankId: "",
      questionId: "",
      practiceSessionId: "",
      studentId: "",
      collaborationRoomId: "",
      classroomId: "",
      identityUserId: ""
    },
    draft: {
      assignment: null,
      questionBank: null,
      question: null,
      grade: null,
      profile: null,
      reminder: null,
      knowledgePath: { goalText: "object collaboration service boundary", days: 5 },
      knowledgePractice: { conceptIds: "", limit: 4 },
      knowledgeContext: { question: "How should the AI answer cite retrieved knowledge?", limit: 4 },
      adaptivePlan: { questionCount: 8, bankId: "" },
      collaborationRoom: { title: "", type: "course", description: "" },
      collaborationTask: { title: "", priority: "medium", assigneeId: "" },
      collaborationSummary: { summary: "", decisions: "", risks: "" },
      collaborationMember: { userId: "", displayName: "", role: "member" },
      collaborationDecision: { title: "", status: "proposed" },
      collaborationResource: { title: "", url: "", type: "link" },
      collaborationChecklist: { title: "", ownerId: "", status: "open" },
      collaborationHandoff: { title: "", toUserId: "", status: "open" },
      classroom: { name: "", courseId: "", courseTitle: "", teacherId: "", capacity: 60, status: "active" },
      classAssignment: { userId: "", role: "student", status: "active" },
      group: { classroomId: "", name: "", leaderId: "", status: "active" },
      groupMember: { groupId: "", userId: "", role: "member", status: "active" },
      identityProfile: { name: "", status: "active", role: "student", department: "", major: "", studentNo: "", teacherNo: "", phone: "" }
    },
    ui: {
      activePanel: "",
      dirtyForms: {},
      focusedQuestionId: ""
    },
    dashboard: null,
    assessment: {
      assignments: [],
      assignmentDetail: null,
      rubrics: [],
      questionBanks: [],
      questions: [],
      mistakes: [],
      practiceSession: null,
      practiceHistory: []
    },
    analytics: {
      overview: null,
      teacher: null,
      selectedCourse: null,
      selectedStudent: null
    },
    workbench: {
      notifications: [],
      notificationSummary: null,
      notificationPreferences: null,
      reminders: [],
      schedulerDashboard: null,
      schedulerTimeline: [],
      schedulerDuePreview: null,
      funnel: null,
      riskBoard: null,
      engagement: null,
      courseDeepReport: null,
      studentProgress: null
    },
    knowledge: {
      summary: null,
      concepts: [],
      selectedConcept: null,
      searchResults: [],
      graph: null,
      recommendations: [],
      learningPath: null,
      practiceSet: null,
      aiContext: null
    },
    assessmentInsight: {
      gradingOverview: null,
      rubricInsight: null,
      submissionInsight: null,
      sessionReview: null,
      adaptivePlan: null,
      mistakeAnalysis: null,
      mistakeDetail: null,
      courseReport: null,
      studentPortfolio: null,
      riskRegister: null
    },
    collaboration: {
      rooms: [],
      workspace: null,
      mentions: [],
      tasks: [],
      decisions: [],
      resources: [],
      checklist: [],
      handoffs: [],
      insight: null,
      audit: []
    },
    reports: {
      catalog: null,
      studentWeekly: null,
      courseWeekly: null,
      assignmentGrading: null,
      mistakeReview: null,
      aiUsage: null,
      exportPreview: null
    },
    identityAdmin: {
      users: [],
      selectedProfile: null,
      classrooms: [],
      classroomDetail: null,
      groups: [],
      roleMatrix: null,
      dashboard: null
    },
    settings: {
      health: null,
      modelConfig: null
    }
  };
}
