import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const output = join(root, "server", "src", "domain", "learningResourceCatalog.generated.js");

const courses = [
  ["course_ood", "面向对象技术与方法"],
  ["course_ai", "人工智能应用实践"],
  ["course_project", "软件项目管理"],
  ["course_frontend", "移动 Web 前端开发"],
  ["course_backend", "服务端架构与接口设计"]
];

const topics = [
  "领域建模",
  "UML 用例分析",
  "类职责分配",
  "设计模式",
  "微服务边界",
  "认证与鉴权",
  "任务拆解",
  "LLM 提示词",
  "学习计划",
  "协作沟通",
  "测试验证",
  "部署运维"
];

const verbs = ["识别", "比较", "实现", "评估", "重构", "验证", "总结", "演示"];
const levels = ["入门", "进阶", "项目实践", "复盘"];

function pick(list, index) {
  return list[index % list.length];
}

const resources = [];
for (let i = 1; i <= 2600; i += 1) {
  const course = pick(courses, i);
  const topic = pick(topics, i * 3);
  const verb = pick(verbs, i * 5);
  const level = pick(levels, i * 7);
  const sprint = Math.ceil(i / 40);
  const concept = `${topic}能力点 ${String(i).padStart(3, "0")}`;
  resources.push({
    id: `res_${String(i).padStart(4, "0")}`,
    courseId: course[0],
    courseTitle: course[1],
    topic,
    concept,
    level,
    sprint,
    scenario: `在第 ${sprint} 个迭代中，学生需要${verb}${topic}相关知识，并把它落实到 EduMind Agent 的项目证据中。`,
    checklist: [
      `说明${concept}的适用场景和输入输出。`,
      `给出至少一个与${topic}相关的类、接口或服务协作。`,
      `用测试、截图或文档段落证明${concept}已经落地。`
    ],
    promptHint: `回答${topic}问题时，优先结合课程“${course[1]}”和项目迭代 ${sprint} 的上下文。`,
    quiz: {
      question: `${concept}最适合用来解决哪类项目问题？`,
      answer: `它适合解决${topic}中需要${verb}、验证并形成项目证据的问题。`
    }
  });
}

const lines = [];
lines.push("// This file is generated by scripts/generateResourceCatalog.mjs.");
lines.push("// It is checked in as project source so the local AI tutor can work without network access.");
lines.push("export const LEARNING_RESOURCE_CATALOG = Object.freeze([");
for (const item of resources) {
  lines.push("  Object.freeze({");
  lines.push(`    id: ${JSON.stringify(item.id)},`);
  lines.push(`    courseId: ${JSON.stringify(item.courseId)},`);
  lines.push(`    courseTitle: ${JSON.stringify(item.courseTitle)},`);
  lines.push(`    topic: ${JSON.stringify(item.topic)},`);
  lines.push(`    concept: ${JSON.stringify(item.concept)},`);
  lines.push(`    level: ${JSON.stringify(item.level)},`);
  lines.push(`    sprint: ${item.sprint},`);
  lines.push(`    scenario: ${JSON.stringify(item.scenario)},`);
  lines.push("    checklist: Object.freeze([");
  for (const check of item.checklist) {
    lines.push(`      ${JSON.stringify(check)},`);
  }
  lines.push("    ]),");
  lines.push(`    promptHint: ${JSON.stringify(item.promptHint)},`);
  lines.push("    quiz: Object.freeze({");
  lines.push(`      question: ${JSON.stringify(item.quiz.question)},`);
  lines.push(`      answer: ${JSON.stringify(item.quiz.answer)}`);
  lines.push("    })");
  lines.push("  }),");
}
lines.push("]);");
lines.push("");
lines.push("export function searchLearningResources(query, limit = 5) {");
lines.push("  const tokens = String(query || \"\").toLowerCase().split(/\\s+|，|。|、|；|：|,|\\.|;|:/).filter(Boolean);");
lines.push("  const scored = LEARNING_RESOURCE_CATALOG.map((item) => {");
lines.push("    const haystack = `${item.courseTitle} ${item.topic} ${item.concept} ${item.scenario} ${item.promptHint}`.toLowerCase();");
lines.push("    const score = tokens.reduce((sum, token) => sum + (haystack.includes(token) ? 1 : 0), 0);");
lines.push("    return { item, score };");
lines.push("  });");
lines.push("  return scored");
lines.push("    .filter((entry) => entry.score > 0)");
lines.push("    .sort((a, b) => b.score - a.score || a.item.id.localeCompare(b.item.id))");
lines.push("    .slice(0, limit)");
lines.push("    .map((entry) => entry.item);");
lines.push("}");
lines.push("");
lines.push("export function resourcesByCourse(courseId) {");
lines.push("  return LEARNING_RESOURCE_CATALOG.filter((item) => item.courseId === courseId);");
lines.push("}");
lines.push("");

await mkdir(dirname(output), { recursive: true });
await writeFile(output, `${lines.join("\n")}\n`, "utf8");
console.log(`Generated ${resources.length} resources at ${output}`);
